### ISSUE TITLE
Destination address has wrong length for GMP transfer

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-explorer-indexer#105]
## Implementation details

Destination address has wrong length, hence link to the explorer will desplay invalid address once user arrives to the block explorer

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-explorer-indexer/105?planning-poker) with Zenhub @tcar121293 @wainola
