### ISSUE TITLE
Update endpoint to search by txHash adding chainId as optional parameter

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-explorer-indexer#115]
Since there is the chance -small one-, that txHash could not be unique, we should fetch transfer passing txHash + chainId

## Implementation details

- update current endpoint to receive chainId as optional parameter

## Testing details

- update test to reflect the change

## Acceptance Criteria

- tests are passing
- we are able to fetch transfer by txHash + chainId

**Comment by mpetrun5** [comment]
The issue is not with the chainID (though I guess that might be a consideration as well but hash collision is very unlikely).
The issue is that someone can program a contract that creates multiple transfers in the same transaction hash.
