### ISSUE TITLE
Deposits stuck in pending state when multiple deposits in one tx

### ISSUE THREAD

**Issue by tcar121293** [sygmaprotocol/sygma-explorer-indexer#155]
This problem became obvious as we prepared a multichain deployment tool for production. Indexer does not store correctly deposit. It looks like transfers are pending, even when we can confirm on chain that the transfers passed successfuly
## Current Behavior
executed transfers are stored as pending without fee data

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Versions
ChainBridge commit (or docker tag):
chainbridge-solidity version:
chainbridge-substrate version:
Go version:

**Comment by LyonSsS** [comment]
fixed in https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/156  ( proof of validation in epic https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/sygma-explorer-indexer/170 )
