### ISSUE TITLE
Release Explorer v1.0.9

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-explorer-indexer#170]
## Details
This version brings a few smaller bug fixes.

[Full changelog for specific changes](https://github.com/sygmaprotocol/sygma-explorer-indexer/releases/tag/v1.0.9)

**Comment by LyonSsS** [comment]
https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/153 fix is now done by https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/168 & https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/156

**Comment by LyonSsS** [comment]
https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/152 fixed for existing duplicates; Only 2 new entries after removal <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16df47f19cd7075f5fef382d509a77fdff0c32ee/image.png" alt="image.png" />

**Comment by LyonSsS** [comment]
https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/161 - not for QA. Notifications are working as is

**Comment by LyonSsS** [comment]
https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/164 - fixed behavior and fixed the issue that caused fees to fail. Cannot be tested

**Comment by LyonSsS** [comment]
https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/166 - indexing now starts after txHash block + 10 <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f7637702024a8d37dc637116caf544e7758cab6/image.png" alt="image.png" />

**Comment by LyonSsS** [comment]
https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/156 <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11404a62ede037a3ce107953aa5f7ea35ff6e89e/image.png" alt="image.png" />
<img width="1210" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05fbbe4ed52920b9e7d8ee7df392eef05f057d29/image.png" alt="image.png" />

**Comment by LyonSsS** [comment]
Issue https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/168  is still not optimal and it should be closed after implementing https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/sygma-explorer-indexer/178 
This is the last open issue on this epic

**Comment by tcar121293** [comment]
We decided that we will skip the implementation of https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/sygma-explorer-indexer/178 for now, since this will cause only an issue on our testnet, because only there we have this specific case where one resourceID has different decimals on different networks

**Comment by LyonSsS** [comment]
Thanks for letting me know. Then this ticket is considered as closed from QA view.
