### ISSUE TITLE
Bridge Transaction not logged by indexer (Testnet)

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-explorer-indexer#183]
Context: Transaction send from Sepolia to Rhala, was not picked up at all: Deposit Tx not logged in DB.
https://sepolia.etherscan.io/tx/0xac2d593db056bb32f225faa9cea5d324d5ffb2729d079fcd80f3686e0dc932cd 
![image](https://github.com/sygmaprotocol/sygma-explorer-indexer/assets/30255634/dc338afc-b7e2-45e9-a32c-6e03091dde39)

NOTE: The deposit TX contains destination address in EVM format and not Substrate format. This TX failed on destination. 
![image](https://github.com/sygmaprotocol/sygma-explorer-indexer/assets/30255634/5064c10b-28bd-4a7c-ade1-38d1f1d8e508)
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frhala-node.phala.network%2Fws#/explorer/query/0x208ddf24b9dadb41085d8351f186c6939a752d79f1e4f66977ec2e6240c332dc | Block height: 535,810

**Comment by MakMuftic** [comment]
Closing this for now as we will migrate to new indexer
