### ISSUE TITLE
Add boolean property to OFAC addresses

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-explorer-indexer#38]
We need to comply to check OFAC addresses by adding a boolean property to the model.

## Implementation details

- add boolean flag to the model
- update indexer work to reflect those changes

## Testing details

- update unit tests

## Acceptance Criteria

- transfers have this property

**Comment by itsbobbyzzz168** [comment]
Moved to Explorer UI 1.5 Epic.
