### ISSUE TITLE
Review optional fields on schema

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-explorer-indexer#48]
Currently we have a bunch of optional fields on the schema, and for some of them this optionality doesn't make too much sense. Revisit this in conjunction with the indexing logic.

## Implementation details

- sender and timesteamp shouldn't be nullable
- check the other fields

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-explorer-indexer/48?planning-poker) with Zenhub @tcar121293 @wainola
