### ISSUE TITLE
USD Value on indexer

### ISSUE THREAD

**Issue by itsbobbyzzz168** [sygmaprotocol/sygma-explorer-indexer#92]
### Description

We would like to implement the USD value for the Explorer UI via a single API (coingecko API) to avoid any calculation.

Consideraitons:
- Use the coinmarket API that the fee oracle is potentially already using (confirm with Freddy)
- see design

**Comment by itsbobbyzzz168** [comment]
[Uploading... Screenshot 2023-07-27 at 15.53.47.png]

**Comment by itsbobbyzzz168** [comment]
<img width="1063" alt="Screenshot 2023-07-27 at 16 20 19" src="https://github.com/sygmaprotocol/sygma-explorer-indexer/assets/134932101/791c6a2a-b557-4004-85e5-6c182a4207d3">

**Comment by mpetrun5** [comment]
We have design for this:
![image](https://github.com/sygmaprotocol/sygma-explorer-indexer/assets/22918781/46df77f9-17df-4be9-9157-ced332985084)

**Comment by itsbobbyzzz168** [comment]
Ah nice thanks @mpetrun5 . @wainola lets just follow this design. i have added the link in https://github.com/sygmaprotocol/explorer-ui/issues/60 (but also here).

Explorer UI with USD value design[https://www.figma.com/file/fNeWCeNeOylnvS5UdFD8CY/Sygma-UI?type=design&node-id=931-3592&mode=design&t=TUuAYWHZdx9kiLC7-0](url)

**Comment by wainola** [comment]
update after sync:

- if API returns error, handle error and save transfers without value (null or zero)
- if we don't provide API url to the service, we should store default value (null or zero)
